src/main/java/org/project/Method.java
=> Merge Method with Developer Branch

src/main/java/org/project/Storage.java
Putting the storage class that I've worked on into the developer branch of the code.
=> Pushing working storage to storage branch

src/main/java/org/project/Load.java, src/main/java/org/project/Save.java
We were able to grab a json file and load the contents to the Treemap that is found in the storage.
we edited the save file to save the TreeMap structure correctly to the json file.
=> Finished Load Feature

src/main/java/org/project/RelationshipMethods.java
The syntax for the add/remove relationship go as the following: deleteRelation [sourceClassName] [destinationClassName]
It will then grab the source class object and add/remove the relationship from there. Hopefully this helps
=> Finished Add/remove Relationship

src/main/test/java/org/project/MethodTest.java
Added Method Unit Test (Along with the file pathway, hopefully that's properly implemented without any conflict)
=> Added Method Unit Test

src/main/java/org/project/Class.java, src/main/java/org/project/ClassCommands.java, src/main/java/org/project/RelationshipMethods.java
Fixed overloading issue and provided feedback on whether an operation was successful or not.
=> Command bugs

src/main/java/org/project/Controller/MainController.java
=> Feature-Add/Rename/Delete

src/main/java/org/project/Controller/MainController.java
* Added functionality to the delete field button.
* Added functionality to the rename field button.
* Added functionality to the add parameter button.
* Added functionality to the add method button.
=> Feature-Delete/Rename/Add

src/main/java/org/project/Controller/MainController.java, src/main/java/org/project/View/ClassNode.java, src/main/resources/Main.fxml, src/main/resources/classNode.fxml
* Deleted button renameClass and saveClassName.
* Added button setClassName.
* Deleted the parameter label.
* Removed textbox and autotab for relationship.
* Modified buttons From and To (made them drop downs) where class will populate.
* Modified the className, so it's not editable through the class box, only inspector.
* Completely removed handleSaveClassName in the main controller.
* Added nameinput.clear() in every method, so when the user adds or renames the textbox clears.
* Remove unnecessary print statements(not needed).
* Added functionality to the Delete Method button.
* Added functionality to the Rename Method button.
=> Feature-added/deleted

src/main/java/org/project/Controller/MainController.java
* Buttons "From" and "To" in the relationship section can now auto populate class names.
=> Feature - auto populate

src/main/java/org/project/Main.java
A new feature allows running a JAR file with two new arguments, --gui and --cli.
=> feature: Main now accepts "--gui" and "--cli" arguments

.github/maven.yml, pom.xml
A GitHub action that checks and builds projects. The action runs when the src directory is modified. The JAR file will be added to the releases if the build and tests pass.
=> GitHub actions

pom.xml, src/test/java/UMLControllerTests.java
Created precondition tests for all subclasses within UMLController.
=> Created UMLController Tests

README.md, src/main/java/org/project/View/CLIView.java
=> Updated README and help commands

saveFile.json, src/main/java/org/project/Controller/MainController.java, src/main/java/org/project/Controller/UMLController.java, src/main/java/org/project/Model/UMLModel.java, src/main/java/org/project/View/ClassBox.java, src/main/java/org/project/View/ClassNode.java
A lot of stuff in a single commit, again :(
=> Add btn gui

src/main/java/org/project/Controller/MainController.java, src/main/java/org/project/Controller/UMLController.java
=> feature: add method from GUI

src/main/java/org/project/Controller/MainController.java
New feature: rename and remove method from GUI
=> feature: remove and rename method

src/main/java/org/project/Controller/MainController.java
Relationship arrows can be added and deleted.
=> Feature   relationship arrows

src/main/java/org/project/Controller/MainController.java
Fixed relationship arrows(on the gui).
=> Bug - relationship arrow

src/main/test/java/org/project/CLIViewTests.java, src/main/test/java/org/project/ClassBoxTest.java
=> more tests

src/main/java/org/project/Controller/GUIViewController.java
* There was an issue with the add parameter where it wouldn't let you add parameters to certain methods.
=> Fixed bug with add parameter

README.md, src/main/java/org/project/Controller/CommandParser.java, src/main/java/org/project/Main.java, src/main/java/org/project/Model/CommandInfo.java, src/main/java/org/project/Model/CommandRegistry.java, src/main/java/org/project/View/Terminal.java, src/test/java/org/project/CommandParserPrintTest.java
v3.3.55 NEW CLI preview(alpha)
=> v3.3.55 NEW CLI preview(alpha)

src/main/java/org/project/Controller/CommandParser.java, src/main/java/org/project/Model/AutoComplete.java, src/main/java/org/project/Model/CommandLogic.java, src/main/java/org/project/Model/CommandRegistries.java, src/main/java/org/project/Model/Storage.java, src/main/java/org/project/Model/UMLClassNode.java, src/main/java/org/project/View/CommandLineTerminal.java
Command Logic being implemented
=> Started working on storage

src/main/java/org/project/Controller/ClassNodeService.java, src/main/java/org/project/Model/CommandLogic.java, src/main/java/org/project/Model/CommandRegistries.java, src/main/resources/CLICommands.json, src/main/resources/NodesClassStorage.json
Method overloading does not work
add parameters is buggy
redo/undo do not work
remove parameters needs refactoring
=> Save/load Fixed bugs for command logic

src/main/java/org/project/Memento/Caretaker.java, src/main/java/org/project/Memento/Memento.java, src/main/java/org/project/Model/CommandLogic.java, src/main/java/org/project/Model/CommandRegistries.java, src/main/java/org/project/Model/Storage.java, src/main/java/org/project/Model/UMLClassNode.java
* added functionality to undo/redo
* Fixed minor bugs
=> Implemented memento design pattern

patterns.md, src/test/java/org/project/MementosCaretakerTest.java
Created a test file for Mementos
Added documentation for Patterns, listing code lines for the mementos pattern, and very briefly defined MVC pattern
=> Tests and Documents for Mementos

patterns.md
Wrote more design patterns to the file.
=> Patterns refactor

src/main/java/org/project/Controller/CommandBridge.java, src/main/java/org/project/Controller/CommandBridgeAdapter.java, src/main/java/org/project/Controller/GraphicalUserInterfaceController.java
* Save to any folder in your machine
* Load from any folder in your machine
* No more overlapping when you save from CLI and load in GUI.
(Relationship arrows still overlap)
=> FEATURE - Save between CLI and GUI
